Map<String, Map<String, String>> allTranslations = {
  'en': {
    'Calculate Loan Page': 'Calculate Loan Page',
    'Salary': 'Salary',
    'Loan Amount': 'Loan Amount',
    'Down Payment': 'Down Payment',
    'Interest Rate (%)': 'Interest Rate (%)',
    'Loan Period (years)': 'Loan Period (years)',
    'Calculate': 'Calculate',
    'Loan Amount: ': 'Loan Amount: ',
    'Monthly Payment: ': 'Monthly Payment: ',
    'Total Payment: ': 'Total Payment: ',
    'You can get this loan.': 'You can get this loan.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.',
  },
  'tr': {
    'Calculate Loan Page': 'Kredi Hesapla',
    'Salary': 'Maaş',
    'Loan Amount': 'Kredi Tutarı',
    'Down Payment': 'Peşinat',
    'Interest Rate (%)': 'Faiz Oranı (%)',
    'Loan Period (years)': 'Kredi Süresi (yıl)',
    'Calculate': 'Hesapla',
    'Loan Amount: ': 'Kredi Tutarı: ',
    'Monthly Payment: ': 'Aylık Ödeme: ',
    'Total Payment: ': 'Toplam Ödeme: ',
    'You can get this loan.': 'Bu krediyi alabilirsiniz.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'Aylık ödeme, maaşınızın %35\'ini aştığı için bu krediyi alamazsınız.',
  },
  'fr': {
    'Calculate Loan Page': 'Calculer le prêt',
    'Salary': 'Salaire',
    'Loan Amount': 'Montant du prêt',
    'Down Payment': 'Paiement initial',
    'Interest Rate (%)': 'Taux d\'intérêt (%)',
    'Loan Period (years)': 'Durée du prêt (années)',
    'Calculate': 'Calculer',
    'Loan Amount: ': 'Montant du prêt : ',
    'Monthly Payment: ': 'Paiement mensuel : ',
    'Total Payment: ': 'Paiement total : ',
    'You can get this loan.': 'Vous pouvez obtenir ce prêt.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'Vous ne pouvez pas obtenir ce prêt car le paiement mensuel dépasse 35% de votre salaire.',
  },
};