Map<String, Map<String, String>> allTranslations = {
  'en': {
    'Food': 'Food',
    'Transportation': 'Transportation',
    'Shopping': 'Shopping',
    'Entertainment': 'Entertainment',
    'Bills': 'Bills',
    'Others': 'Others',
    'Product Name': 'Product Name',
    'Initial Value': 'Initial Value',
    'Save': 'Save',
    'Update': 'Update',
    'New Value': 'New Value',
    'Inflation Page': 'Inflation Page',
    'Calculate': 'Calculate',
    'Reset': 'Reset',
    'Remaining Days:': 'Remaining Days:',
    'Daily Expense Amount:': 'Daily Expense Amount:',
    'Inflation': 'Inflation',
  },
  'tr': {
    'Food': 'Yiyecek',
    'Transportation': 'Ulaşım',
    'Shopping': 'Alışveriş',
    'Entertainment': 'Eğlence',
    'Bills': 'Faturalar',
    'Others': 'Diğerleri',
    'Product Name': 'Ürün Adı',
    'Initial Value': 'İlk Değer',
    'Save': 'Kaydet',
    'Update': 'Güncelle',
    'New Value': 'Yeni Değer',
    'Inflation Page': 'Enflasyon Sayfası',
    'Calculate': 'Hesapla',
    'Reset': 'Sıfırla',
    'Remaining Days:': 'Kalan Günler:',
    'Daily Expense Amount:': 'Günlük Harcama Miktarı:',
    'Inflation': 'Enflasyon',
  },
  'fr': {
    'Food': 'Alimentation',
    'Transportation': 'Transport',
    'Shopping': 'Shopping',
    'Entertainment': 'Divertissement',
    'Bills': 'Factures',
    'Others': 'Autres',
    'Product Name': 'Nom du Produit',
    'Initial Value': 'Valeur Initiale',
    'Save': 'Enregistrer',
    'Update': 'Mettre à jour',
    'New Value': 'Nouvelle Valeur',
    'Inflation Page': 'Page de l\'Inflation',
    'Calculate': 'Calculer',
    'Reset': 'Réinitialiser',
    'Remaining Days:': 'Jours Restants :',
    'Daily Expense Amount:': 'Montant des Dépenses Quotidiennes :',
    'Inflation': 'Inflation',
  },
};