Map<String, Map<String, String>> allTranslations = {
  'en': {
    'Salary Calculation': 'Salary Calculation',
    'How long do I need to work?': 'How long do I need to work?',
    'Your Salary': 'Your Salary',
    'Product Price': 'Product Price',
    'Calculate': 'Calculate',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.',
    'Calculate Loan Page': 'Calculate Loan Page',
    'Salary': 'Salary',
    'Loan Amount': 'Loan Amount',
    'Down Payment': 'Down Payment',
    'Interest Rate (%)': 'Interest Rate (%)',
    'Loan Period (years)': 'Loan Period (years)',
    'Loan Amount: ': 'Loan Amount: ',
    'Monthly Payment: ': 'Monthly Payment: ',
    'Total Payment: ': 'Total Payment: ',
    'You can get this loan.': 'You can get this loan.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.',
    'Currency Converter': 'Currency Converter',
    'Amount': 'Amount',
    'Select Currency': 'Select Currency',
    'Convert': 'Convert',
    'Converted Amount': 'Converted Amount',
    'Close': 'Close',
    'Search...': 'Search...',
    'Expense Tracker': 'Expense Tracker',
    'Total Expenses': 'Total Expenses',
    'Expense Type': 'Expense Type',
    'Add Expense': 'Add Expense',
    'No expenses recorded': 'No expenses recorded',
    'Total Expense': 'Total Expense',
    'January': 'January',
    'February': 'February',
    'March': 'March',
    'April': 'April',
    'May': 'May',
    'June': 'June',
    'July': 'July',
    'August': 'August',
    'September': 'September',
    'October': 'October',
    'November': 'November',
    'December': 'December',
    'Food': 'Food',
    'Transportation': 'Transportation',
    'Shopping': 'Shopping',
    'Entertainment': 'Entertainment',
    'Bills': 'Bills',
    'Others': 'Others',
    'How Much Can I Spend?': 'How Much Can I Spend?',
    'Income Amount': 'Income Amount',
    'Future Date (yyyy-MM-dd)': 'Future Date (yyyy-MM-dd)',
    'Subtraction Value': 'Subtraction Value',
    'Subtract from Value': 'Subtract from Value',
    'Remaining Days:': 'Remaining Days:',
    'Daily Expense Amount:': 'Daily Expense Amount:',
    'Reset': 'Reset',
    'OK': 'OK',
    'Cancel': 'Cancel',
    'Select Date': 'Select Date',
    'Income Page': 'Income Page',
    'Select Start Date': 'Select Start Date',
    'Start Date': 'Start Date',
    'End Date': 'End Date',
    'Add Income': 'Add Income',
    'Update Income Amount': 'Update Income Amount',
    'Save': 'Save',
    'Edit': 'Edit',
    'Delete': 'Delete',
    'Product Name': 'Product Name',
    'Initial Value': 'Initial Value',
    'Update': 'Update',
    'New Value': 'New Value',
    'Inflation Page': 'Inflation Page',
    'Inflation': 'Inflation',
    'Income': 'Income',
    'Expense': 'Expense',
    'How much to spend daily': 'How much to spend daily',
    'Calculate To Buy': 'Calculate To Buy',
    'Calculate Loan': 'Calculate Loan',
    'Exchange': 'Exchange',
    'Total Income': 'Total Income',
    'Amount: ': 'Amount: ',
    'Date: ': 'Date: ',
  },
  'tr': {
    'Salary Calculation': 'Maaş Hesaplama',
    'How long do I need to work?': 'Ne kadar süre çalışmam gerekiyor?',
    'Your Salary': 'Maaşınız',
    'Product Price': 'Ürün Fiyatı',
    'Calculate': 'Hesapla',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'İstenilen ürünü almak için {years} yıl, {months} ay ve {days} gün çalışmanız gerekiyor.',
    'Calculate Loan Page': 'Kredi Hesapla',
    'Salary': 'Maaş',
    'Loan Amount': 'Kredi Tutarı',
    'Down Payment': 'Peşinat',
    'Interest Rate (%)': 'Faiz Oranı (%)',
    'Loan Period (years)': 'Kredi Süresi (yıl)',
    'Loan Amount: ': 'Kredi Tutarı: ',
    'Monthly Payment: ': 'Aylık Ödeme: ',
    'Total Payment: ': 'Toplam Ödeme: ',
    'You can get this loan.': 'Bu krediyi alabilirsiniz.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'Aylık ödeme, maaşınızın %35\'ini aştığı için bu krediyi alamazsınız.',
    'Currency Converter': 'Para Dönüştürücüsü',
    'Amount': 'Miktar',
    'Select Currency': 'Para Birimi Seç',
    'Convert': 'Dönüştür',
    'Converted Amount': 'Dönüştürülen Miktar',
    'Close': 'Kapat',
    'Search...': 'Ara...',
    'Expense Tracker': 'Harcama Takipçisi',
    'Total Expenses': 'Toplam Harcamalar',
    'Expense Type': 'Harcama Türü',
    'Add Expense': 'Harcama Ekle',
    'No expenses recorded': 'Kaydedilen harcama yok',
    'Total Expense': 'Toplam Harcama',
    'January': 'Ocak',
    'February': 'Şubat',
    'March': 'Mart',
    'April': 'Nisan',
    'May': 'Mayıs',
    'June': 'Haziran',
    'July': 'Temmuz',
    'August': 'Ağustos',
    'September': 'Eylül',
    'October': 'Ekim',
    'November': 'Kasım',
    'December': 'Aralık',
    'Food': 'Yemek',
    'Transportation': 'Ulaşım',
    'Shopping': 'Alışveriş',
    'Entertainment': 'Eğlence',
    'Bills': 'Faturalar',
    'Others': 'Diğer',
    'How Much Can I Spend?': 'Ne Kadar Harcayabilirim?',
    'Income Amount': 'Gelir Miktarı',
    'Future Date (yyyy-MM-dd)': 'Gelecek Tarih (yyyy-AA-gg)',
    'Subtraction Value': 'Çıkarma Değeri',
    'Subtract from Value': 'Değerden Çıkar',
    'Remaining Days:': 'Kalan Günler:',
    'Daily Expense Amount:': 'Günlük Harcama Miktarı:',
    'Reset': 'Sıfırla',
    'OK': 'Seç',
    'Cancel': 'Vazgeç',
    'Select Date': 'Tarih Seçin',
    'Income Page': 'Gelir Sayfası',
    'Select Start Date': 'Başlangıç Tarihini Seç',
    'Start Date': 'Başlangıç Tarihi',
    'End Date': 'Bitiş Tarihi',
    'Add Income': 'Gelir Ekle',
    'Update Income Amount': 'Gelir Miktarını Güncelle',
    'Save': 'Kaydet',
    'Edit': 'Düzenle',
    'Delete': 'Sil',
    'Product Name': 'Ürün Adı',
    'Initial Value': 'İlk Değer',
    'Update': 'Güncelle',
    'New Value': 'Yeni Değer',
    'Inflation Page': 'Enflasyon Sayfası',
    'Inflation': 'Enflasyon',
    'Income': 'Gelir',
    'Expense': 'Gider',
    'How much to spend daily': 'Günlük harcamanız ne kadar olmalı',
    'Calculate To Buy': 'Almak ne kadar sürer',
    'Calculate Loan': 'Kredi Hesapla',
    'Exchange': 'Döviz Hesaplama',
    'Total Income': 'Toplam Gelir',
    'Amount: ': 'Miktar: ',
    'Date: ': 'Tarih: ',
  },
  'fr': {
    'Salary Calculation': 'Calcul du salaire',
    'How long do I need to work?': 'Combien de temps dois-je travailler?',
    'Your Salary': 'Votre salaire',
    'Product Price': 'Prix du produit',
    'Calculate': 'Calculer',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'Vous devez travailler pendant {years} années, {months} mois et {days} jours pour acheter le produit souhaité.',
    'Calculate Loan Page': 'Calculer le prêt',
    'Salary': 'Salaire',
    'Loan Amount': 'Montant du prêt',
    'Down Payment': 'Paiement initial',
    'Interest Rate (%)': 'Taux d\'intérêt (%)',
    'Loan Period (years)': 'Durée du prêt (années)',
    'Loan Amount: ': 'Montant du prêt : ',
    'Monthly Payment: ': 'Paiement mensuel : ',
    'Total Payment: ': 'Paiement total : ',
    'You can get this loan.': 'Vous pouvez obtenir ce prêt.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'Vous ne pouvez pas obtenir ce prêt car le paiement mensuel dépasse 35% de votre salaire.',
    'Currency Converter': 'Convertisseur de devises',
    'Amount': 'Montant',
    'Select Currency': 'Sélectionner la devise',
    'Convert': 'Convertir',
    'Converted Amount': 'Montant converti',
    'Close': 'Fermer',
    'Search...': 'Rechercher...',
    'Expense Tracker': 'Suivi des dépenses',
    'Total Expenses': 'Total des dépenses',
    'Expense Type': 'Type de dépense',
    'Add Expense': 'Ajouter une dépense',
    'No expenses recorded': 'Aucune dépense enregistrée',
    'Total Expense': 'Total des dépenses',
    'January': 'Janvier',
    'February': 'Février',
    'March': 'Mars',
    'April': 'Avril',
    'May': 'Mai',
    'June': 'Juin',
    'July': 'Juillet',
    'August': 'Août',
    'September': 'Septembre',
    'October': 'Octobre',
    'November': 'Novembre',
    'December': 'Décembre',
    'Food': 'Nourriture',
    'Transportation': 'Transport',
    'Shopping': 'Shopping',
    'Entertainment': 'Divertissement',
    'Bills': 'Factures',
    'Others': 'Autres',
    'How Much Can I Spend?': 'Combien puis-je dépenser ?',
    'Income Amount': 'Montant des revenus',
    'Future Date (yyyy-MM-dd)': 'Date future (aaaa-MM-jj)',
    'Subtraction Value': 'Valeur à soustraire',
    'Subtract from Value': 'Soustraire de la valeur',
    'Remaining Days:': 'Jours restants :',
    'Daily Expense Amount:': 'Montant des dépenses quotidiennes :',
    'Reset': 'Réinitialiser',
    'OK': 'OK',
    'Cancel': 'Annuler',
    'Select Date': 'Sélectionner la date',
    'Income Page': 'Page des Revenus',
    'Select Start Date': 'Sélectionner la date de début',
    'Start Date': 'Date de début',
    'End Date': 'Date de fin',
    'Add Income': 'Ajouter un revenu',
    'Update Income Amount': 'Mettre à jour le montant des revenus',
    'Save': 'Enregistrer',
    'Edit': 'Modifier',
    'Delete': 'Supprimer',
    'Product Name': 'Nom du Produit',
    'Initial Value': 'Valeur Initiale',
    'Update': 'Mettre à jour',
    'New Value': 'Nouvelle Valeur',
    'Inflation Page': 'Page de l\'Inflation',
    'Inflation': 'Inflation',
    'Income': 'Revenu',
    'Expense': 'Dépense',
    'How much to spend daily': 'Combien dépenser par jour',
    'Calculate To Buy': 'Calculer l\'achat',
    'Calculate Loan': 'Calculer le prêt',
    'Exchange': 'Calcul de change',
    'Total Income': 'Revenu Total',
    'Amount: ': 'Montant : ',
    'Date: ': 'Date : ',
  },
};