Map<String, Map<String, String>> allTranslations = {
  'en': {
    'Salary Calculation': 'Salary Calculation',
    'How long do I need to work?': 'How long do I need to work?',
    'Your Salary': 'Your Salary',
    'Product Price': 'Product Price',
    'Calculate': 'Calculate',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.',
    'Calculate Loan Page': 'Calculate Loan Page',
    'Salary': 'Salary',
    'Loan Amount': 'Loan Amount',
    'Down Payment': 'Down Payment',
    'Interest Rate (%)': 'Interest Rate (%)',
    'Loan Period (years)': 'Loan Period (years)',
    'Loan Amount: ': 'Loan Amount: ',
    'Monthly Payment: ': 'Monthly Payment: ',
    'Total Payment: ': 'Total Payment: ',
    'You can get this loan.': 'You can get this loan.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.',
    'Currency Converter': 'Currency Converter',
    'Amount': 'Amount',
    'Select Currency': 'Select Currency',
    'Convert': 'Convert',
    'Converted Amount': 'Converted Amount',
    'Close': 'Close',
    'Search...': 'Search...',
    'Expense Tracker': 'Expense Tracker',
    'Total Expenses': 'Financial Summary',
    'Expense Type': 'Expense Type',
    'Add Expense': 'Add Expense',
    'No expenses recorded': 'No expenses recorded',
    'Total Expense': 'Financial Summary',
    'January': 'January',
    'February': 'February',
    'March': 'March',
    'April': 'April',
    'May': 'May',
    'June': 'June',
    'July': 'July',
    'August': 'August',
    'September': 'September',
    'October': 'October',
    'November': 'November',
    'December': 'December',
    'Food': 'Food',
    'Transportation': 'Transportation',
    'Shopping': 'Shopping',
    'Entertainment': 'Entertainment',
    'Bills': 'Bills',
    'Others': 'Others',
    'How Much Can I Spend?': 'How Much Can I Spend?',
    'Income Amount': 'Income Amount',
    'Future Date (yyyy-MM-dd)': 'Future Date (yyyy-MM-dd)',
    'Subtraction Value': 'Expense Value',
    'Subtract from Value': 'I Spent',
    'Remaining Days:': 'Remaining Days:',
    'Daily Expense Amount:': 'Daily Expense Amount:',
    'Reset': 'Reset',
    'OK': 'OK',
    'Cancel': 'Cancel',
    'Select Date': 'Select Date',
    'Income Page': 'Income Page',
    'Select Start Date': 'Select Start Date',
    'Start Date': 'Start Date',
    'End Date': 'End Date',
    'Add Income': 'Add Income',
    'Update Income Amount': 'Update Income Amount',
    'Save': 'Save',
    'Edit': 'Edit',
    'Delete': 'Delete',
    'Product Name': 'Product Name',
    'Initial Value': 'Initial Value',
    'Update': 'Update',
    'New Value': 'New Value',
    'Inflation Page': 'Inflation Page',
    'Inflation': 'Inflation',
    'Price Index Calculator': 'Price Index Calculator',
    'Income': 'Income',
    'Expense': 'Expense',
    'How much to spend daily': 'How Much To Spend Daily',
    'Calculate To Buy': 'Calculate To Buy',
    'Calculate Loan': 'Calculate Loan',
    'Exchange': 'Exchange',
    'Total Income': 'Total Income',
    'Amount: ': 'Amount: ',
    'Date: ': 'Date: ',
    'Settings': 'Settings',
    'Languages': 'Languages',
    'Clear Application Data': 'Clear Application Data',
    'Clear Data': 'Clear Data',
    'Are you sure you want to clear all user data ?': 'Are you sure you want to clear all user data ?',
    'Select Color': 'Select Color',
    'BlueGrey': 'BlueGrey',
    'Red': 'Red',
    'Green': 'Green',
    'Yellow': 'Yellow',
    'Orange': 'Orange',
    'Purple': 'Purple',
    'Pink': 'Pink',
    'Teal': 'Teal',
    'Cyan': 'Cyan',
    'Amber': 'Amber',
    'Deep Purple': 'Deep Purple',
    'Indigo': 'Indigo',
    'Change Background Color': 'Change Background Color',
    'Application Settings': 'Application Settings',
    'Yearly': 'Yearly',
    'Monthly': 'Monthly',
    'Year': 'Year',
    'Month': 'Month',
    'Select': 'Select',
  },
  'tr': {
    'Salary Calculation': 'Maaş Hesaplama',
    'How long do I need to work?': 'Ne kadar süre çalışmam gerekiyor?',
    'Your Salary': 'Maaşınız',
    'Product Price': 'Ürün Fiyatı',
    'Calculate': 'Hesapla',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'İstenilen ürünü almak için {years} yıl, {months} ay ve {days} gün çalışmanız gerekiyor.',
    'Calculate Loan Page': 'Kredi Hesapla',
    'Salary': 'Maaş',
    'Loan Amount': 'Kredi Tutarı',
    'Down Payment': 'Peşinat',
    'Interest Rate (%)': 'Faiz Oranı (%)',
    'Loan Period (years)': 'Kredi Süresi (yıl)',
    'Loan Amount: ': 'Kredi Tutarı: ',
    'Monthly Payment: ': 'Aylık Ödeme: ',
    'Total Payment: ': 'Toplam Ödeme: ',
    'You can get this loan.': 'Bu krediyi alabilirsiniz.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'Aylık ödeme, maaşınızın %35\'ini aştığı için bu krediyi alamazsınız.',
    'Currency Converter': 'Para Dönüştürücüsü',
    'Amount': 'Miktar',
    'Select Currency': 'Para Birimi Seç',
    'Convert': 'Dönüştür',
    'Converted Amount': 'Dönüştürülen Miktar',
    'Close': 'Kapat',
    'Search...': 'Ara...',
    'Expense Tracker': 'Harcama Takipçisi',
    'Total Expenses': 'Hesap Dökümü',
    'Expense Type': 'Harcama Türü',
    'Add Expense': 'Harcama Ekle',
    'No expenses recorded': 'Kaydedilen harcama yok',
    'Total Expense': 'Hesap Dökümü',
    'January': 'Ocak',
    'February': 'Şubat',
    'March': 'Mart',
    'April': 'Nisan',
    'May': 'Mayıs',
    'June': 'Haziran',
    'July': 'Temmuz',
    'August': 'Ağustos',
    'September': 'Eylül',
    'October': 'Ekim',
    'November': 'Kasım',
    'December': 'Aralık',
    'Food': 'Yemek',
    'Transportation': 'Ulaşım',
    'Shopping': 'Alışveriş',
    'Entertainment': 'Eğlence',
    'Bills': 'Faturalar',
    'Others': 'Diğer',
    'How Much Can I Spend?': 'Ne Kadar Harcayabilirim?',
    'Income Amount': 'Gelir Miktarı',
    'Future Date (yyyy-MM-dd)': 'Gelecek Tarih (yyyy-AA-gg)',
    'Subtraction Value': 'Harcama Değeri',
    'Subtract from Value': 'Harcadım',
    'Remaining Days:': 'Kalan Günler:',
    'Daily Expense Amount:': 'Günlük Harcama Miktarı:',
    'Reset': 'Sıfırla',
    'OK': 'Seç',
    'Cancel': 'Vazgeç',
    'Select Date': 'Tarih Seçin',
    'Income Page': 'Gelir Sayfası',
    'Select Start Date': 'Başlangıç Tarihini Seç',
    'Start Date': 'Başlangıç Tarihi',
    'End Date': 'Bitiş Tarihi',
    'Add Income': 'Gelir Ekle',
    'Update Income Amount': 'Gelir Miktarını Güncelle',
    'Save': 'Kaydet',
    'Edit': 'Düzenle',
    'Delete': 'Sil',
    'Product Name': 'Ürün Adı',
    'Initial Value': 'İlk Değer',
    'Update': 'Güncelle',
    'New Value': 'Yeni Değer',
    'Inflation Page': 'Enflasyon Sayfası',
    'Inflation': 'Enflasyon',
    'Price Index Calculator': 'Kendi Enflasyonunu Tut',
    'Income': 'Gelir',
    'Expense': 'Gider',
    'How much to spend daily': 'Günlük Ne Kadar Harcamalıyım',
    'Calculate To Buy': 'Almak Ne Kadar Sürer',
    'Calculate Loan': 'Kredi Hesapla',
    'Exchange': 'Döviz Hesaplama',
    'Total Income': 'Toplam Gelir',
    'Amount: ': 'Miktar: ',
    'Date: ': 'Tarih: ',
    'Settings': 'Ayarlar',
    'Languages': 'Dil Seçenekleri',
    'Clear Application Data': 'Uygulama Verilerini Temizle',
    'Clear Data': 'Verileri Temizle',
    'Are you sure you want to clear all user data ?': 'Tüm kullanıcı verilerini silmek istediğinizden emin misiniz?',
    'Select Color': 'Renk Seçin',
    'BlueGrey': 'Mavi Gri',
    'Red': 'Kırmızı',
    'Green': 'Yeşil',
    'Yellow': 'Sarı',
    'Orange': 'Turuncu',
    'Purple': 'Mor',
    'Pink': 'Pembe',
    'Teal': 'Turkuaz',
    'Cyan': 'Cam Göbeği',
    'Amber': 'Amber',
    'Deep Purple': 'Koyu Mor',
    'Indigo': 'İndigo',
    'Change Background Color': 'Arka Plan Rengini Değiştir',
    'Application Settings': 'Uygulama Ayarları',
    'Yearly': 'Yıllık',
    'Monthly': 'Aylık',
    'Year': 'Yıl',
    'Month': 'Ay',
    'Select': 'Seç',
  },
  'fr': {
    'Salary Calculation': 'Calcul du salaire',
    'How long do I need to work?': 'Combien de temps dois-je travailler?',
    'Your Salary': 'Votre salaire',
    'Product Price': 'Prix du produit',
    'Calculate': 'Calculer',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'Vous devez travailler pendant {years} années, {months} mois et {days} jours pour acheter le produit souhaité.',
    'Calculate Loan Page': 'Calculer le prêt',
    'Salary': 'Salaire',
    'Loan Amount': 'Montant du prêt',
    'Down Payment': 'Paiement initial',
    'Interest Rate (%)': 'Taux d\'intérêt (%)',
    'Loan Period (years)': 'Durée du prêt (années)',
    'Loan Amount: ': 'Montant du prêt : ',
    'Monthly Payment: ': 'Paiement mensuel : ',
    'Total Payment: ': 'Paiement total : ',
    'You can get this loan.': 'Vous pouvez obtenir ce prêt.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'Vous ne pouvez pas obtenir ce prêt car le paiement mensuel dépasse 35% de votre salaire.',
    'Currency Converter': 'Convertisseur de devises',
    'Amount': 'Montant',
    'Select Currency': 'Sélectionner la devise',
    'Convert': 'Convertir',
    'Converted Amount': 'Montant converti',
    'Close': 'Fermer',
    'Search...': 'Rechercher...',
    'Expense Tracker': 'Suivi des dépenses',
    'Total Expenses': 'Résumé Financier',
    'Expense Type': 'Type de dépense',
    'Add Expense': 'Ajouter une dépense',
    'No expenses recorded': 'Aucune dépense enregistrée',
    'Total Expense': 'Résumé Financier',
    'January': 'Janvier',
    'February': 'Février',
    'March': 'Mars',
    'April': 'Avril',
    'May': 'Mai',
    'June': 'Juin',
    'July': 'Juillet',
    'August': 'Août',
    'September': 'Septembre',
    'October': 'Octobre',
    'November': 'Novembre',
    'December': 'Décembre',
    'Food': 'Nourriture',
    'Transportation': 'Transport',
    'Shopping': 'Shopping',
    'Entertainment': 'Divertissement',
    'Bills': 'Factures',
    'Others': 'Autres',
    'How Much Can I Spend?': 'Combien puis-je dépenser ?',
    'Income Amount': 'Montant des revenus',
    'Future Date (yyyy-MM-dd)': 'Date future (aaaa-MM-jj)',
    'Subtraction Value': 'Valeur De Dépense',
    'Subtract from Value': 'J\'ai Dépensé',
    'Remaining Days:': 'Jours restants :',
    'Daily Expense Amount:': 'Dépenses Quotidiennes :',
    'Reset': 'Réinitialiser',
    'OK': 'OK',
    'Cancel': 'Annuler',
    'Select Date': 'Sélectionner la date',
    'Income Page': 'Page des Revenus',
    'Select Start Date': 'Sélectionner la date de début',
    'Start Date': 'Date de début',
    'End Date': 'Date de fin',
    'Add Income': 'Ajouter un revenu',
    'Update Income Amount': 'Mettre à jour le montant des revenus',
    'Save': 'Enregistrer',
    'Edit': 'Modifier',
    'Delete': 'Supprimer',
    'Product Name': 'Nom du Produit',
    'Initial Value': 'Valeur Initiale',
    'Update': 'Mettre à jour',
    'New Value': 'Nouvelle Valeur',
    'Inflation Page': 'Page de l\'Inflation',
    'Inflation': 'Inflation',
    'Price Index Calculator': 'Calculateur d\'Indice des Prix',
    'Income': 'Revenu',
    'Expense': 'Dépense',
    'How much to spend daily': 'Combien dépenser par jour',
    'Calculate To Buy': 'Calculer l\'achat',
    'Calculate Loan': 'Calculer le prêt',
    'Exchange': 'Calcul de change',
    'Total Income': 'Revenu Total',
    'Amount: ': 'Montant : ',
    'Date: ': 'Date : ',
    'Settings': 'Paramètres',
    'Languages': 'Langues',
    'Clear Application Data': 'Effacer données',
    'Clear Data': 'Effacer les données',
    'Are you sure you want to clear all user data ?':  'Êtes-vous sûr ?',
    'Select Color': 'Sélectionnez une couleur',
    'BlueGrey': 'Gris Bleu',
    'Red': 'Rouge',
    'Green': 'Vert',
    'Yellow': 'Jaune',
    'Orange': 'Orange',
    'Purple': 'Violet',
    'Pink': 'Rose',
    'Teal': 'Turquoise',
    'Cyan': 'Cyan',
    'Amber': 'Ambre',
    'Deep Purple': 'Violet Foncé',
    'Indigo': 'Indigo',
    'Change Background Color': 'Changer la couleur',
    'Application Settings': 'Paramètres de l\'application',
    'Yearly': 'Annuel',
    'Monthly': 'Mensuel',
    'Year': 'An',
    'Month': 'Mois',
    'Select': 'Sélectionner',
  },
  'de': {
    'Salary Calculation': 'Gehaltsberechnung',
    'How long do I need to work?': 'Wie lange muss ich arbeiten?',
    'Your Salary': 'Dein Gehalt',
    'Product Price': 'Produktpreis',
    'Calculate': 'Berechnen',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'Du musst {years} Jahre, {months} Monate und {days} Tage arbeiten, um das gewünschte Produkt zu kaufen.',
    'Calculate Loan Page': 'Kreditberechnung',
    'Salary': 'Gehalt',
    'Loan Amount': 'Kreditbetrag',
    'Down Payment': 'Anzahlung',
    'Interest Rate (%)': 'Zinssatz (%)',
    'Loan Period (years)': 'Kreditlaufzeit (Jahre)',
    'Loan Amount: ': 'Kreditbetrag: ',
    'Monthly Payment: ': 'Monatliche Zahlung: ',
    'Total Payment: ': 'Gesamtzahlung: ',
    'You can get this loan.': 'Du kannst diesen Kredit erhalten.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'Du kannst diesen Kredit nicht erhalten, da die monatliche Zahlung 35% deines Gehalts überschreitet.',
    'Currency Converter': 'Währungsumrechner',
    'Amount': 'Betrag',
    'Select Currency': 'Währung auswählen',
    'Convert': 'Umwandeln',
    'Converted Amount': 'Umgerechneter Betrag',
    'Close': 'Schließen',
    'Search...': 'Suchen...',
    'Expense Tracker': 'Ausgabenverfolgung',
    'Total Expenses': 'Gesamtausgaben',
    'Expense Type': 'Ausgabentyp',
    'Add Expense': 'Ausgabe hinzufügen',
    'No expenses recorded': 'Keine Ausgaben erfasst',
    'Total Expense': 'Gesamtausgaben',
    'January': 'Januar',
    'February': 'Februar',
    'March': 'März',
    'April': 'April',
    'May': 'Mai',
    'June': 'Juni',
    'July': 'Juli',
    'August': 'August',
    'September': 'September',
    'October': 'Oktober',
    'November': 'November',
    'December': 'Dezember',
    'Food': 'Lebensmittel',
    'Transportation': 'Transport',
    'Shopping': 'Einkaufen',
    'Entertainment': 'Unterhaltung',
    'Bills': 'Rechnungen',
    'Others': 'Sonstiges',
    'How Much Can I Spend?': 'Wie viel kann ich ausgeben?',
    'Income Amount': 'Einkommensbetrag',
    'Future Date (yyyy-MM-dd)': 'Zukünftiges Datum (yyyy-MM-dd)',
    'Subtraction Value': 'Ausgabewert',
    'Subtract from Value': 'Hinzufügen',
    'Remaining Days:': 'Verbleibende Tage:',
    'Daily Expense Amount:': 'Tagesausgaben:',
    'Reset': 'Zurücksetzen',
    'OK': 'OK',
    'Cancel': 'Abbrechen',
    'Select Date': 'Datum auswählen',
    'Income Page': 'Einkommensseite',
    'Select Start Date': 'Startdatum auswählen',
    'Start Date': 'Startdatum',
    'End Date': 'Enddatum',
    'Add Income': 'Einkommen hinzufügen',
    'Update Income Amount': 'Einkommensbetrag aktualisieren',
    'Save': 'Speichern',
    'Edit': 'Bearbeiten',
    'Delete': 'Löschen',
    'Product Name': 'Produktname',
    'Initial Value': 'Anfangswert',
    'Update': 'Aktualisieren',
    'New Value': 'Neuer Wert',
    'Inflation Page': 'Inflationsseite',
    'Inflation': 'Inflation',
    'Price Index Calculator': 'Preisindexrechner',
    'Income': 'Einkommen',
    'Expense': 'Ausgabe',
    'How much to spend daily': 'Wie viel kann ich täglich ausgeben?',
    'Calculate To Buy': 'Kauf berechnen',
    'Calculate Loan': 'Kredit berechnen',
    'Exchange': 'Austausch',
    'Total Income': 'Gesamteinnahmen',
    'Amount: ': 'Betrag: ',
    'Date: ': 'Datum: ',
    'Settings': 'Einstellungen',
    'Languages': 'Sprachen',
    'Clear Application Data': 'Anwendungsdaten löschen',
    'Clear Data': 'Daten löschen',
    'Are you sure you want to clear all user data ?': 'Bist du sicher, dass du alle Benutzerdaten löschen möchtest?',
    'Select Color': 'Farbe auswählen',
    'BlueGrey': 'Blau-Grau',
    'Red': 'Rot',
    'Green': 'Grün',
    'Yellow': 'Gelb',
    'Orange': 'Orange',
    'Purple': 'Lila',
    'Pink': 'Pink',
    'Teal': 'Blaugrün',
    'Cyan': 'Cyan',
    'Amber': 'Bernstein',
    'Deep Purple': 'Dunkelviolett',
    'Indigo': 'Indigo',
    'Change Background Color': 'Hintergrundfarbe ändern',
    'Application Settings': 'Anwendungseinstellungen',
    'Yearly': 'Jährlich',
    'Monthly': 'Monatlich',
    'Year': 'Jahr',
    'Month': 'Monat',
    'Select': 'Auswählen',
  },
  'es': {
    'Salary Calculation': 'Cálculo de Salario',
    'How long do I need to work?': '¿Cuánto tiempo necesito trabajar?',
    'Your Salary': 'Tu Salario',
    'Product Price': 'Precio del Producto',
    'Calculate': 'Calcular',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'Necesitas trabajar {years} años, {months} meses y {days} días para comprar el producto deseado.',
    'Calculate Loan Page': 'Calculadora de Préstamo',
    'Salary': 'Salario',
    'Loan Amount': 'Monto del Préstamo',
    'Down Payment': 'Pago Inicial',
    'Interest Rate (%)': 'Tasa de Interés (%)',
    'Loan Period (years)': 'Plazo del Préstamo (años)',
    'Loan Amount: ': 'Monto del Préstamo: ',
    'Monthly Payment: ': 'Pago Mensual: ',
    'Total Payment: ': 'Pago Total: ',
    'You can get this loan.': 'Puedes obtener este préstamo.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'No puedes obtener este préstamo porque el pago mensual excede el 35% de tu salario.',
    'Currency Converter': 'Convertidor de Moneda',
    'Amount': 'Monto',
    'Select Currency': 'Seleccionar Moneda',
    'Convert': 'Convertir',
    'Converted Amount': 'Monto Convertido',
    'Close': 'Cerrar',
    'Search...': 'Buscar...',
    'Expense Tracker': 'Seguimiento de Gastos',
    'Total Expenses': 'Gastos Totales',
    'Expense Type': 'Tipo de Gasto',
    'Add Expense': 'Agregar Gasto',
    'No expenses recorded': 'No hay gastos registrados',
    'Total Expense': 'Gasto Total',
    'January': 'Enero',
    'February': 'Febrero',
    'March': 'Marzo',
    'April': 'Abril',
    'May': 'Mayo',
    'June': 'Junio',
    'July': 'Julio',
    'August': 'Agosto',
    'September': 'Septiembre',
    'October': 'Octubre',
    'November': 'Noviembre',
    'December': 'Diciembre',
    'Food': 'Comida',
    'Transportation': 'Transporte',
    'Shopping': 'Compras',
    'Entertainment': 'Entretenimiento',
    'Bills': 'Facturas',
    'Others': 'Otros',
    'How Much Can I Spend?': '¿Cuánto puedo gastar?',
    'Income Amount': 'Monto de Ingresos',
    'Future Date (yyyy-MM-dd)': 'Fecha Futura (aaaa-MM-dd)',
    'Subtraction Value': 'Valor de Resta',
    'Subtract from Value': 'Restar',
    'Remaining Days:': 'Días Restantes:',
    'Daily Expense Amount:': 'Monto de Gasto Diario:',
    'Reset': 'Reiniciar',
    'OK': 'Aceptar',
    'Cancel': 'Cancelar',
    'Select Date': 'Seleccionar Fecha',
    'Income Page': 'Página de Ingresos',
    'Select Start Date': 'Seleccionar Fecha de Inicio',
    'Start Date': 'Fecha de Inicio',
    'End Date': 'Fecha de Fin',
    'Add Income': 'Agregar Ingreso',
    'Update Income Amount': 'Actualizar Monto de Ingresos',
    'Save': 'Guardar',
    'Edit': 'Editar',
    'Delete': 'Eliminar',
    'Product Name': 'Nombre del Producto',
    'Initial Value': 'Valor Inicial',
    'Update': 'Actualizar',
    'New Value': 'Nuevo Valor',
    'Inflation Page': 'Página de Inflación',
    'Inflation': 'Inflación',
    'Price Index Calculator': 'Calculadora de Índice de Precios',
    'Income': 'Ingreso',
    'Expense': 'Gasto',
    'How much to spend daily': 'Cuánto gastar diariamente',
    'Calculate To Buy': 'Calcular para Comprar',
    'Calculate Loan': 'Calcular Préstamo',
    'Exchange': 'Intercambio',
    'Total Income': 'Ingresos Totales',
    'Amount: ': 'Monto: ',
    'Date: ': 'Fecha: ',
    'Settings': 'Configuración',
    'Languages': 'Idiomas',
    'Clear Application Data': 'Borrar Datos de la Aplicación',
    'Clear Data': 'Borrar Datos',
    'Are you sure you want to clear all user data ?': '¿Estás seguro de que deseas borrar todos los datos del usuario?',
    'Select Color': 'Seleccionar Color',
    'BlueGrey': 'Azul Grisáceo',
    'Red': 'Rojo',
    'Green': 'Verde',
    'Yellow': 'Amarillo',
    'Orange': 'Naranja',
    'Purple': 'Morado',
    'Pink': 'Rosa',
    'Teal': 'Verde Azulado',
    'Cyan': 'Cian',
    'Amber': 'Ámbar',
    'Deep Purple': 'Morado Oscuro',
    'Indigo': 'Índigo',
    'Change Background Color': 'Cambiar Color de Fondo',
    'Application Settings': 'Configuración de la Aplicación',
    'Yearly': 'Anual',
    'Monthly': 'Mensual',
    'Year': 'Año',
    'Month': 'Mes',
    'Select': 'Seleccionar',
  },
  'ja': {
    'Salary Calculation': '給与計算',
    'How long do I need to work?': 'どのくらい働く必要がありますか？',
    'Your Salary': 'あなたの給料',
    'Product Price': '製品価格',
    'Calculate': '計算',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    '希望する製品を購入するには、{years} 年 {months} か月 {days} 日働く必要があります。',
    'Calculate Loan Page': 'ローン計算',
    'Salary': '給与',
    'Loan Amount': 'ローン金額',
    'Down Payment': '頭金',
    'Interest Rate (%)': '利率（%）',
    'Loan Period (years)': 'ローン期間（年）',
    'Loan Amount: ': 'ローン金額：',
    'Monthly Payment: ': '月々の支払い：',
    'Total Payment: ': '総支払額：',
    'You can get this loan.': 'このローンを利用できます。',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    '月々の支払額が給与の35％を超えるため、このローンを利用することはできません。',
    'Currency Converter': '通貨コンバータ',
    'Amount': '金額',
    'Select Currency': '通貨を選択',
    'Convert': '変換',
    'Converted Amount': '変換後の金額',
    'Close': '閉じる',
    'Search...': '検索...',
    'Expense Tracker': '経費トラッカー',
    'Total Expenses': '総支出',
    'Expense Type': '経費タイプ',
    'Add Expense': '経費を追加',
    'No expenses recorded': '経費は記録されていません',
    'Total Expense': '総支出',
    'January': '1月',
    'February': '2月',
    'March': '3月',
    'April': '4月',
    'May': '5月',
    'June': '6月',
    'July': '7月',
    'August': '8月',
    'September': '9月',
    'October': '10月',
    'November': '11月',
    'December': '12月',
    'Food': '食品',
    'Transportation': '交通',
    'Shopping': '買い物',
    'Entertainment': '娯楽',
    'Bills': '請求書',
    'Others': 'その他',
    'How Much Can I Spend?': 'どれだけ使えますか？',
    'Income Amount': '収入金額',
    'Future Date (yyyy-MM-dd)': '将来の日付（yyyy-MM-dd）',
    'Subtraction Value': '引き算の値',
    'Subtract from Value': '値から引く',
    'Remaining Days:': '残りの日数：',
    'Daily Expense Amount:': '1日の経費金額：',
    'Reset': 'リセット',
    'OK': 'OK',
    'Cancel': 'キャンセル',
    'Select Date': '日付を選択',
    'Income Page': '収入ページ',
    'Select Start Date': '開始日を選択',
    'Start Date': '開始日',
    'End Date': '終了日',
    'Add Income': '収入を追加',
    'Update Income Amount': '収入金額を更新',
    'Save': '保存',
    'Edit': '編集',
    'Delete': '削除',
    'Product Name': '製品名',
    'Initial Value': '初期値',
    'Update': '更新',
    'New Value': '新しい値',
    'Inflation Page': 'インフレーションページ',
    'Inflation': '物価上昇',
    'Price Index Calculator': '価格指数計算機',
    'Income': '収入',
    'Expense': '経費',
    'How much to spend daily': '1日にどれだけ使うか',
    'Calculate To Buy': '購入計算',
    'Calculate Loan': 'ローン計算',
    'Exchange': '交換',
    'Total Income': '総収入',
    'Amount: ': '金額：',
    'Date: ': '日付：',
    'Settings': '設定',
    'Languages': '言語',
    'Clear Application Data': 'アプリケーションデータをクリア',
    'Clear Data': 'データをクリア',
    'Are you sure you want to clear all user data ?': 'すべてのユーザーデータを削除してもよろしいですか？',
    'Select Color': '色を選択',
    'BlueGrey': 'ブルーグレー',
    'Red': '赤',
    'Green': '緑',
    'Yellow': '黄',
    'Orange': 'オレンジ',
    'Purple': '紫',
    'Pink': 'ピンク',
    'Teal': 'ティール',
    'Cyan': 'シアン',
    'Amber': 'アンバー',
    'Deep Purple': '濃い紫',
    'Indigo': 'インディゴ',
    'Change Background Color': '背景色の変更',
    'Application Settings': 'アプリケーションの設定',
    'Yearly': '毎年',
    'Monthly': '毎月',
    'Year': '年',
    'Month': '月',
    'Select': '選択',
  },
  'vi': {
    'Salary Calculation': 'Tính Lương',
    'How long do I need to work?': 'Tôi cần làm việc bao lâu?',
    'Your Salary': 'Lương của bạn',
    'Product Price': 'Giá sản phẩm',
    'Calculate': 'Tính toán',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'Bạn cần làm việc trong {years} năm, {months} tháng và {days} ngày để mua sản phẩm mong muốn.',
    'Calculate Loan Page': 'Tính toán Khoản vay',
    'Salary': 'Lương',
    'Loan Amount': 'Số tiền vay',
    'Down Payment': 'Tiền trả trước',
    'Interest Rate (%)': 'Lãi suất (%)',
    'Loan Period (years)': 'Kỳ hạn vay (năm)',
    'Loan Amount: ': 'Số tiền vay: ',
    'Monthly Payment: ': 'Thanh toán hàng tháng: ',
    'Total Payment: ': 'Tổng thanh toán: ',
    'You can get this loan.': 'Bạn có thể nhận khoản vay này.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'Bạn không thể nhận khoản vay này vì khoản thanh toán hàng tháng vượt quá 35% lương của bạn.',
    'Currency Converter': 'Bộ chuyển đổi tiền tệ',
    'Amount': 'Số tiền',
    'Select Currency': 'Chọn loại tiền tệ',
    'Convert': 'Chuyển đổi',
    'Converted Amount': 'Số tiền đã chuyển đổi',
    'Close': 'Đóng',
    'Search...': 'Tìm kiếm...',
    'Expense Tracker': 'Theo dõi Chi tiêu',
    'Total Expenses': 'Tổng chi tiêu',
    'Expense Type': 'Loại chi tiêu',
    'Add Expense': 'Thêm chi tiêu',
    'No expenses recorded': 'Không có chi tiêu ghi lại',
    'Total Expense': 'Tổng chi tiêu',
    'January': 'Tháng 1',
    'February': 'Tháng 2',
    'March': 'Tháng 3',
    'April': 'Tháng 4',
    'May': 'Tháng 5',
    'June': 'Tháng 6',
    'July': 'Tháng 7',
    'August': 'Tháng 8',
    'September': 'Tháng 9',
    'October': 'Tháng 10',
    'November': 'Tháng 11',
    'December': 'Tháng 12',
    'Food': 'Ăn uống',
    'Transportation': 'Giao thông',
    'Shopping': 'Mua sắm',
    'Entertainment': 'Giải trí',
    'Bills': 'Hóa đơn',
    'Others': 'Khác',
    'How Much Can I Spend?': 'Tôi có thể tiêu bao nhiêu?',
    'Income Amount': 'Số tiền thu nhập',
    'Future Date (yyyy-MM-dd)': 'Ngày tương lai (yyyy-MM-dd)',
    'Subtraction Value': 'Số tiền chi',
    'Subtract from Value': 'Tôi đã tiêu',
    'Remaining Days:': 'Số ngày còn lại:',
    'Daily Expense Amount:': 'Số tiền chi hàng ngày:',
    'Reset': 'Đặt lại',
    'OK': 'OK',
    'Cancel': 'Hủy',
    'Select Date': 'Chọn ngày',
    'Income Page': 'Trang Thu nhập',
    'Select Start Date': 'Chọn Ngày bắt đầu',
    'Start Date': 'Ngày bắt đầu',
    'End Date': 'Ngày kết thúc',
    'Add Income': 'Thêm Thu nhập',
    'Update Income Amount': 'Cập nhật Số tiền thu nhập',
    'Save': 'Lưu',
    'Edit': 'Chỉnh sửa',
    'Delete': 'Xóa',
    'Product Name': 'Tên sản phẩm',
    'Initial Value': 'Giá trị ban đầu',
    'Update': 'Cập nhật',
    'New Value': 'Giá trị mới',
    'Inflation Page': 'Trang Lạm phát',
    'Inflation': 'Lạm phát',
    'Price Index Calculator': 'Máy tính chỉ số giá',
    'Income': 'Thu nhập',
    'Expense': 'Chi tiêu',
    'How much to spend daily': 'Tiêu bao nhiêu hàng ngày',
    'Calculate To Buy': 'Tính toán để mua',
    'Calculate Loan': 'Tính toán Khoản vay',
    'Exchange': 'Trao đổi',
    'Total Income': 'Tổng thu nhập',
    'Amount: ': 'Số tiền: ',
    'Date: ': 'Ngày: ',
    'Settings': 'Cài đặt',
    'Languages': 'Ngôn ngữ',
    'Clear Application Data': 'Xóa Dữ liệu Ứng dụng',
    'Clear Data': 'Xóa Dữ liệu',
    'Are you sure you want to clear all user data ?': 'Bạn có chắc chắn muốn xóa tất cả dữ liệu người dùng?',
    'Select Color': 'Chọn Màu sắc',
    'BlueGrey': 'Xám-xanh',
    'Red': 'Đỏ',
    'Green': 'Xanh lá cây',
    'Yellow': 'Vàng',
    'Orange': 'Cam',
    'Purple': 'Tím',
    'Pink': 'Hồng',
    'Teal': 'Xanh da trời',
    'Cyan': 'Xanh lam',
    'Amber': 'Hổ phách',
    'Deep Purple': 'Tím đậm',
    'Indigo': 'Mầu chàm',
    'Change Background Color': 'Thay đổi Màu nền',
    'Application Settings': 'Cài đặt Ứng dụng',
    'Yearly': 'Hàng năm',
    'Monthly': 'Hàng tháng',
    'Year': 'Năm',
    'Month': 'Tháng',
    'Select': 'Chọn',
  },
  'zh': {
    'Salary Calculation': '薪水計算',
    'How long do I need to work?': '我需要工作多久？',
    'Your Salary': '你的薪水',
    'Product Price': '產品價格',
    'Calculate': '計算',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    '你需要工作 {years} 年，{months} 月，和 {days} 天才能買到所需的產品。',
    'Calculate Loan Page': '貸款計算頁面',
    'Salary': '薪水',
    'Loan Amount': '貸款金額',
    'Down Payment': '首付款',
    'Interest Rate (%)': '利率（%）',
    'Loan Period (years)': '貸款期限（年）',
    'Loan Amount: ': '貸款金額：',
    'Monthly Payment: ': '月付款：',
    'Total Payment: ': '總付款：',
    'You can get this loan.': '你可以獲得這筆貸款。',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    '你無法獲得這筆貸款，因為月付款金額超過你薪水的35%。',
    'Currency Converter': '貨幣轉換器',
    'Amount': '金額',
    'Select Currency': '選擇貨幣',
    'Convert': '轉換',
    'Converted Amount': '轉換後的金額',
    'Close': '關閉',
    'Search...': '搜索...',
    'Expense Tracker': '費用追蹤器',
    'Total Expenses': '財務摘要',
    'Expense Type': '費用類型',
    'Add Expense': '添加費用',
    'No expenses recorded': '沒有記錄費用',
    'Total Expense': '財務摘要',
    'January': '一月',
    'February': '二月',
    'March': '三月',
    'April': '四月',
    'May': '五月',
    'June': '六月',
    'July': '七月',
    'August': '八月',
    'September': '九月',
    'October': '十月',
    'November': '十一月',
    'December': '十二月',
    'Food': '食物',
    'Transportation': '交通',
    'Shopping': '購物',
    'Entertainment': '娛樂',
    'Bills': '帳單',
    'Others': '其他',
    'How Much Can I Spend?': '我能花多少錢？',
    'Income Amount': '收入金額',
    'Future Date (yyyy-MM-dd)': '未來日期（yyyy-MM-dd）',
    'Subtraction Value': '減去金額',
    'Subtract from Value': '我花了',
    'Remaining Days:': '剩餘天數：',
    'Daily Expense Amount:': '每日花費金額：',
    'Reset': '重置',
    'OK': '確定',
    'Cancel': '取消',
    'Select Date': '選擇日期',
    'Income Page': '收入頁面',
    'Select Start Date': '選擇開始日期',
    'Start Date': '開始日期',
    'End Date': '結束日期',
    'Add Income': '添加收入',
    'Update Income Amount': '更新收入金額',
    'Save': '保存',
    'Edit': '編輯',
    'Delete': '刪除',
    'Product Name': '產品名稱',
    'Initial Value': '初始價值',
    'Update': '更新',
    'New Value': '新價值',
    'Inflation Page': '通脹頁面',
    'Inflation': '通脹',
    'Price Index Calculator': '價格指數計算器',
    'Income': '收入',
    'Expense': '費用',
    'How much to spend daily': '每日花費多少錢',
    'Calculate To Buy': '計算購買',
    'Calculate Loan': '計算貸款',
    'Exchange': '匯率',
    'Total Income': '總收入',
    'Amount: ': '金額：',
    'Date: ': '日期：',
    'Settings': '設定',
    'Languages': '語言',
    'Clear Application Data': '清除應用程式數據',
    'Clear Data': '清除數據',
    'Are you sure you want to clear all user data ?': '確定要清除所有使用者數據嗎？',
    'Select Color': '選擇顏色',
    'BlueGrey': '藍灰色',
    'Red': '紅色',
    'Green': '綠色',
    'Yellow': '黃色',
    'Orange': '橙色',
    'Purple': '紫色',
    'Pink': '粉紅色',
    'Teal': '青色',
    'Cyan': '藍綠色',
    'Amber': '黃褐色',
    'Deep Purple': '深紫色',
    'Indigo': '靛色',
    'Change Background Color': '更改背景顏色',
    'Application Settings': '應用程式設定',
    'Yearly': '每年',
    'Monthly': '每月',
    'Year': '年',
    'Month': '月',
    'Select': '选择',
  },
  'ar': {
    'Salary Calculation': 'حساب الراتب',
    'How long do I need to work?': 'كم من الوقت يتعين علي أن أعمل؟',
    'Your Salary': 'راتبك',
    'Product Price': 'سعر المنتج',
    'Calculate': 'احسب',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'تحتاج إلى العمل لمدة {years} سنة و {months} شهرًا و {days} يومًا لشراء المنتج المطلوب.',
    'Calculate Loan Page': 'صفحة حساب القرض',
    'Salary': 'الراتب',
    'Loan Amount': 'مبلغ القرض',
    'Down Payment': 'الدفعة الأولى',
    'Interest Rate (%)': 'نسبة الفائدة (%)',
    'Loan Period (years)': 'فترة القرض (سنوات)',
    'Loan Amount: ': 'مبلغ القرض: ',
    'Monthly Payment: ': 'الدفعة الشهرية: ',
    'Total Payment: ': 'إجمالي المبلغ المدفوع: ',
    'You can get this loan.': 'يمكنك الحصول على هذا القرض.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'لا يمكنك الحصول على هذا القرض لأن الدفعة الشهرية تتجاوز 35% من راتبك.',
    'Currency Converter': 'محول العملات',
    'Amount': 'المبلغ',
    'Select Currency': 'اختر العملة',
    'Convert': 'تحويل',
    'Converted Amount': 'المبلغ المحول',
    'Close': 'إغلاق',
    'Search...': 'بحث...',
    'Expense Tracker': 'تتبع المصروفات',
    'Total Expenses': 'الملخص المالي',
    'Expense Type': 'نوع المصروف',
    'Add Expense': 'إضافة مصروف',
    'No expenses recorded': 'لم يتم تسجيل أي مصروفات',
    'Total Expense': 'الملخص المالي',
    'January': 'يناير',
    'February': 'فبراير',
    'March': 'مارس',
    'April': 'أبريل',
    'May': 'مايو',
    'June': 'يونيو',
    'July': 'يوليو',
    'August': 'أغسطس',
    'September': 'سبتمبر',
    'October': 'أكتوبر',
    'November': 'نوفمبر',
    'December': 'ديسمبر',
    'Food': 'الطعام',
    'Transportation': 'النقل',
    'Shopping': 'التسوق',
    'Entertainment': 'الترفيه',
    'Bills': 'الفواتير',
    'Others': 'أخرى',
    'How Much Can I Spend?': 'كم يمكنني أن أنفق؟',
    'Income Amount': 'مبلغ الدخل',
    'Future Date (yyyy-MM-dd)': 'تاريخ المستقبل (yyyy-MM-dd)',
    'Subtraction Value': 'قيمة النفقة',
    'Subtract from Value': 'لقد أنفقت',
    'Remaining Days:': 'الأيام المتبقية:',
    'Daily Expense Amount:': 'Mصروف يومي: ',
    'Reset': 'إعادة تعيين',
    'OK': 'موافق',
    'Cancel': 'إلغاء',
    'Select Date': 'اختر تاريخ',
    'Income Page': 'صفحة الدخل',
    'Select Start Date': 'اختر تاريخ البدء',
    'Start Date': 'تاريخ البدء',
    'End Date': 'تاريخ الانتهاء',
    'Add Income': 'إضافة دخل',
    'Update Income Amount': 'تحديث مبلغ الدخل',
    'Save': 'حفظ',
    'Edit': 'تحرير',
    'Delete': 'حذف',
    'Product Name': 'اسم المنتج',
    'Initial Value': 'القيمة الأولية',
    'Update': 'تحديث',
    'New Value': 'القيمة الجديدة',
    'Inflation Page': 'صفحة التضخم',
    'Inflation': 'التضخم',
    'Price Index Calculator': 'آلة حاسبة لمؤشر الأسعار',
    'Income': 'الدخل',
    'Expense': 'المصروف',
    'How much to spend daily': 'كم يمكن أن أنفق يوميًا',
    'Calculate To Buy': 'حساب الشراء',
    'Calculate Loan': 'حساب القرض',
    'Exchange': 'صرف',
    'Total Income': 'إجمالي الدخل',
    'Amount: ': 'المبلغ: ',
    'Date: ': 'التاريخ: ',
    'Settings': 'الإعدادات',
    'Languages': 'اللغات',
    'Clear Application Data': 'مسح بيانات التطبيق',
    'Clear Data': 'مسح البيانات',
    'Are you sure you want to clear all user data ?': 'هل أنت متأكد من أنك تريد مسح جميع بيانات المستخدم؟',
    'Select Color': 'اختر اللون',
    'BlueGrey': 'أزرق رمادي',
    'Red': 'أحمر',
    'Green': 'أخضر',
    'Yellow': 'أصفر',
    'Orange': 'برتقالي',
    'Purple': 'أرجواني',
    'Pink': 'وردي',
    'Teal': 'تركوازي',
    'Cyan': 'سماوي',
    'Amber': 'عنبري',
    'Deep Purple': 'أرجواني داكن',
    'Indigo': 'نيلي',
    'Change Background Color': 'تغيير لون الخلفية',
    'Application Settings': 'إعدادات التطبيق',
    'Yearly': 'سنوي',
    'Monthly': 'شهري',
    'Year': 'سنة',
    'Month': 'شهر',
    'Select': 'اختر',
  },
  'ru': {
    'Salary Calculation': 'Расчет заработной платы',
    'How long do I need to work?': 'Сколько времени мне нужно работать?',
    'Your Salary': 'Ваша зарплата',
    'Product Price': 'Цена товара',
    'Calculate': 'Рассчитать',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'Вам нужно работать {years} лет, {months} месяцев и {days} дней, чтобы купить желаемый товар.',
    'Calculate Loan Page': 'Страница расчета займа',
    'Salary': 'Зарплата',
    'Loan Amount': 'Сумма займа',
    'Down Payment': 'Первоначальный взнос',
    'Interest Rate (%)': 'Процентная ставка (%)',
    'Loan Period (years)': 'Срок займа (в годах)',
    'Loan Amount: ': 'Сумма займа: ',
    'Monthly Payment: ': 'Ежемесячный платеж: ',
    'Total Payment: ': 'Общий платеж: ',
    'You can get this loan.': 'Вы можете получить этот займ.',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'Вы не можете получить этот займ, так как ежемесячный платеж превышает 35% от вашей зарплаты.',
    'Currency Converter': 'Конвертер валют',
    'Amount': 'Сумма',
    'Select Currency': 'Выбрать валюту',
    'Convert': 'Конвертировать',
    'Converted Amount': 'Конвертированная сумма',
    'Close': 'Закрыть',
    'Search...': 'Поиск...',
    'Expense Tracker': 'Учет расходов',
    'Total Expenses': 'Общая сумма расходов',
    'Expense Type': 'Тип расхода',
    'Add Expense': 'Добавить расход',
    'No expenses recorded': 'Нет записей о расходах',
    'Total Expense': 'Общая сумма расходов',
    'January': 'Январь',
    'February': 'Февраль',
    'March': 'Март',
    'April': 'Апрель',
    'May': 'Май',
    'June': 'Июнь',
    'July': 'Июль',
    'August': 'Август',
    'September': 'Сентябрь',
    'October': 'Октябрь',
    'November': 'Ноябрь',
    'December': 'Декабрь',
    'Food': 'Питание',
    'Transportation': 'Транспорт',
    'Shopping': 'Шопинг',
    'Entertainment': 'Развлечения',
    'Bills': 'Счета',
    'Others': 'Другое',
    'How Much Can I Spend?': 'Сколько я могу потратить?',
    'Income Amount': 'Сумма дохода',
    'Future Date (yyyy-MM-dd)': 'Дата в будущем (гггг-ММ-дд)',
    'Subtraction Value': 'Сумма расхода',
    'Subtract from Value': 'Я потратил',
    'Remaining Days:': 'Оставшиеся дни:',
    'Daily Expense Amount:': 'Ежедневная сумма расходов:',
    'Reset': 'Сбросить',
    'OK': 'OK',
    'Cancel': 'Отмена',
    'Select Date': 'Выбрать дату',
    'Income Page': 'Страница доходов',
    'Select Start Date': 'Выберите начальную дату',
    'Start Date': 'Дата начала',
    'End Date': 'Дата окончания',
    'Add Income': 'Добавить доход',
    'Update Income Amount': 'Обновить сумму дохода',
    'Save': 'Сохранить',
    'Edit': 'Редактировать',
    'Delete': 'Удалить',
    'Product Name': 'Название товара',
    'Initial Value': 'Исходная стоимость',
    'Update': 'Обновить',
    'New Value': 'Новая стоимость',
    'Inflation Page': 'Страница инфляции',
    'Inflation': 'Инфляция',
    'Price Index Calculator': 'Калькулятор индекса цен',
    'Income': 'Доход',
    'Expense': 'Расход',
    'How much to spend daily': 'Сколько тратить ежедневно',
    'Calculate To Buy': 'Рассчитать для покупки',
    'Calculate Loan': 'Рассчитать займ',
    'Exchange': 'Обмен',
    'Total Income': 'Общий доход',
    'Amount: ': 'Сумма: ',
    'Date: ': 'Дата: ',
    'Settings': 'Настройки',
    'Languages': 'Языки',
    'Clear Application Data': 'Очистить данные приложения',
    'Clear Data': 'Очистить данные',
    'Are you sure you want to clear all user data ?': 'Вы уверены, что хотите очистить все пользовательские данные?',
    'Select Color': 'Выбрать цвет',
    'BlueGrey': 'Серо-голубой',
    'Red': 'Красный',
    'Green': 'Зеленый',
    'Yellow': 'Желтый',
    'Orange': 'Оранжевый',
    'Purple': 'Пурпурный',
    'Pink': 'Розовый',
    'Teal': 'Бирюзовый',
    'Cyan': 'Голубой',
    'Amber': 'Янтарный',
    'Deep Purple': 'Темно-пурпурный',
    'Indigo': 'Индиго',
    'Change Background Color': 'Изменить цвет фона',
    'Application Settings': 'Настройки приложения',
    'Yearly': 'Ежегодно',
    'Monthly': 'Ежемесячно',
    'Year': 'Год',
    'Month': 'Месяц',
    'Select': 'Выбрать',
  },
  'hi': {
    'Salary Calculation': 'वेतन की गणना',
    'How long do I need to work?': 'मुझे कितनी देर काम करनी चाहिए?',
    'Your Salary': 'आपकी वेतन',
    'Product Price': 'उत्पाद की कीमत',
    'Calculate': 'गणना करें',
    'You need to work for {years} years, {months} months, and {days} days to buy the desired product.':
    'आपको चाहिए कि आप {years} साल, {months} महीने और {days} दिन काम करें ताकि आप चाहिए गए उत्पाद को खरीद सकें।',
    'Calculate Loan Page': 'कर्ज की गणना पृष्ठ',
    'Salary': 'वेतन',
    'Loan Amount': 'कर्ज राशि',
    'Down Payment': 'डाउन पेमेंट',
    'Interest Rate (%)': 'ब्याज दर (%)',
    'Loan Period (years)': 'कर्ज अवधि (साल)',
    'Loan Amount: ': 'कर्ज राशि: ',
    'Monthly Payment: ': 'मासिक भुगतान: ',
    'Total Payment: ': 'कुल भुगतान: ',
    'You can get this loan.': 'आप इस कर्ज को प्राप्त कर सकते हैं।',
    'You cannot get this loan because the monthly payment exceeds 35% of your salary.':
    'आप इस कर्ज को प्राप्त नहीं कर सकते क्योंकि मासिक भुगतान आपके वेतन के 35% से अधिक है।',
    'Currency Converter': 'मुद्रा परिवर्तक',
    'Amount': 'राशि',
    'Select Currency': 'मुद्रा चुनें',
    'Convert': 'परिवर्तित करें',
    'Converted Amount': 'परिवर्तित राशि',
    'Close': 'बंद करें',
    'Search...': 'खोजें...',
    'Expense Tracker': 'खर्च ट्रैकर',
    'Total Expenses': 'वित्तीय सारांश',
    'Expense Type': 'व्यय प्रकार',
    'Add Expense': 'व्यय जोड़ें',
    'No expenses recorded': 'कोई खर्च दर्ज नहीं किया गया है',
    'Total Expense': 'वित्तीय सारांश',
    'January': 'जनवरी',
    'February': 'फरवरी',
    'March': 'मार्च',
    'April': 'अप्रैल',
    'May': 'मई',
    'June': 'जून',
    'July': 'जुलाई',
    'August': 'अगस्त',
    'September': 'सितंबर',
    'October': 'अक्टूबर',
    'November': 'नवंबर',
    'December': 'दिसंबर',
    'Food': 'खाना',
    'Transportation': 'यातायात',
    'Shopping': 'खरीदारी',
    'Entertainment': 'मनोरंजन',
    'Bills': 'बिल',
    'Others': 'अन्य',
    'How Much Can I Spend?': 'मैं कितना खर्च कर सकता हूँ?',
    'Income Amount': 'आय राशि',
    'Future Date (yyyy-MM-dd)': 'भविष्य की तारीख (yyyy-MM-dd)',
    'Subtraction Value': 'व्यय राशि',
    'Subtract from Value': 'मैंने खर्च किया',
    'Remaining Days:': 'शेष दिन:',
    'Daily Expense Amount:': 'दैनिक व्यय राशि:',
    'Reset': 'रीसेट',
    'OK': 'ठीक',
    'Cancel': 'रद्द करें',
    'Select Date': 'तारीख चुनें',
    'Income Page': 'आय पृष्ठ',
    'Select Start Date': 'प्रारंभ तिथि चुनें',
    'Start Date': 'प्रारंभ तिथि',
    'End Date': 'समाप्ति तिथि',
    'Add Income': 'आय जोड़ें',
    'Update Income Amount': 'आय राशि अपडेट करें',
    'Save': 'सहेजें',
    'Edit': 'संपादित करें',
    'Delete': 'हटाएं',
    'Product Name': 'उत्पाद का नाम',
    'Initial Value': 'प्रारंभिक मूल्य',
    'Update': 'अपडेट',
    'New Value': 'नई मूल्य',
    'Inflation Page': 'मुद्रास्फीति पृष्ठ',
    'Inflation': 'मुद्रास्फीति',
    'Price Index Calculator': 'मूल्य सूचकांक कैलकुलेटर',
    'Income': 'आय',
    'Expense': 'व्यय',
    'How much to spend daily': 'दैनिक रूप से कितना खर्च करना है',
    'Calculate To Buy': 'खरीदने के लिए गणना करें',
    'Calculate Loan': 'कर्ज की गणना करें',
    'Exchange': 'विनिमय',
    'Total Income': 'कुल आय',
    'Amount: ': 'राशि: ',
    'Date: ': 'तारीख: ',
    'Settings': 'सेटिंग्स',
    'Languages': 'भाषाएँ',
    'Clear Application Data': 'आवेदन डेटा साफ़ करें',
    'Clear Data': 'डेटा साफ़ करें',
    'Are you sure you want to clear all user data ?': 'क्या आप सुनिश्चित हैं कि आप सभी उपयोगकर्ता डेटा को साफ़ करना चाहते हैं?',
    'Select Color': 'रंग चुनें',
    'BlueGrey': 'नीला-धूसर',
    'Red': 'लाल',
    'Green': 'हरा',
    'Yellow': 'पीला',
    'Orange': 'नारंगी',
    'Purple': 'बैंगनी',
    'Pink': 'गुलाबी',
    'Teal': 'हरिताभ',
    'Cyan': 'सियान',
    'Amber': 'पीला हरिताभ',
    'Deep Purple': 'गहरा बैंगनी',
    'Indigo': 'नीला',
    'Change Background Color': 'पृष्ठभूमि का रंग बदलें',
    'Application Settings': 'आवेदन सेटिंग्स',
    'Yearly': 'सालाना',
    'Monthly': 'मासिक',
    'Year': 'साल',
    'Month': 'महीना',
    'Select': 'चुनें',
  },
};