Map<String, Map<String, String>> translations = {
  'en': {
    'Income': 'Income',
    'Expense': 'Expense',
    'Total Expense': 'Total Expense',
    'Inflation': 'Inflation',
    'How much to spend daily': 'How much to spend daily',
    'Calculate To Buy': 'Calculate To Buy',
    'Calculate Loan': 'Calculate Loan',
    'Exchange': 'Exchange',
  },
  'tr': {
    'Income': 'Gelir',
    'Expense': 'Gider',
    'Total Expense': 'Toplam Gider',
    'Inflation': 'Enflasyon',
    'How much to spend daily': 'Günlük harcamanız ne kadar olmalı',
    'Calculate To Buy': 'Almak ne kadar sürer',
    'Calculate Loan': 'Kredi Hesapla',
    'Exchange': 'Döviz Hesaplama',
  },
  'fr': {
    'Income': 'Revenu',
    'Expense': 'Dépense',
    'Total Expense': 'Total des dépenses',
    'Inflation': 'Inflation',
    'How much to spend daily': 'Combien dépenser par jour',
    'Calculate To Buy': 'Calculer l\'achat',
    'Calculate Loan': 'Calculer le prêt',
    'Exchange': 'Calcul de change',
  },
};