Map<String, Map<String, String>> allTranslations = {
  'en': {
    'Total Expenses': 'Total Expenses',
    'Total Expense': 'Total Expense',
    'Total Income': 'Total Income',
    'Amount: ': 'Amount: ',
    'Date: ': 'Date: ',
    'January': 'January',
    'February': 'February',
    'March': 'March',
    'April': 'April',
    'May': 'May',
    'June': 'June',
    'July': 'July',
    'August': 'August',
    'September': 'September',
    'October': 'October',
    'November': 'November',
    'December': 'December',
    'Food': 'Food',
    'Transportation': 'Transportation',
    'Shopping': 'Shopping',
    'Entertainment': 'Entertainment',
    'Bills': 'Bills',
    'Others': 'Others',
  },
  'tr': {
    'Total Expenses': 'Toplam Harcamalar',
    'Total Expense': 'Toplam Harcama',
    'Total Income': 'Toplam Gelir',
    'Amount: ': 'Miktar: ',
    'Date: ': 'Tarih: ',
    'January': 'Ocak',
    'February': 'Şubat',
    'March': 'Mart',
    'April': 'Nisan',
    'May': 'Mayıs',
    'June': 'Haziran',
    'July': 'Temmuz',
    'August': 'Ağustos',
    'September': 'Eylül',
    'October': 'Ekim',
    'November': 'Kasım',
    'December': 'Aralık',
    'Food': 'Yemek',
    'Transportation': 'Ulaşım',
    'Shopping': 'Alışveriş',
    'Entertainment': 'Eğlence',
    'Bills': 'Faturalar',
    'Others': 'Diğer',
  },
  'fr': {
    'Total Expenses': 'Total des Dépenses',
    'Total Expense': 'Dépense Totale',
    'Total Income': 'Revenu Total',
    'Amount: ': 'Montant : ',
    'Date: ': 'Date : ',
    'January': 'Janvier',
    'February': 'Février',
    'March': 'Mars',
    'April': 'Avril',
    'May': 'Mai',
    'June': 'Juin',
    'July': 'Juillet',
    'August': 'Août',
    'September': 'Septembre',
    'October': 'Octobre',
    'November': 'Novembre',
    'December': 'Décembre',
    'Food': 'Nourriture',
    'Transportation': 'Transport',
    'Shopping': 'Shopping',
    'Entertainment': 'Divertissement',
    'Bills': 'Factures',
    'Others': 'Autres',
  },
};
